### ISSUE TITLE
100MB이상의 파일 push하는법 아시는분??

### ISSUE THREAD

**Issue by ZZmarkus** [kpuce2021/Hyeongdori#10]
알려주세요 ㅠㅠ

**Comment by gijeon82** [comment]
구글링하면 몇가지 방법이 나옵니다. https://velog.io/@29been/Github-100MB%EB%B3%B4%EB%8B%A4-%ED%81%B0-%ED%8C%8C%EC%9D%BC-%EC%98%AC%EB%A6%AC%EA%B8%B0

**Comment by gijeon82** [comment]
대용량 file을 uoload하려면 Github Large File Storage를 사용해야하며, 추가적으로 돈을 지불해야합니다.
100M 이상 파일 업로드가 왜 필요한지 알려주기 바랍니다.

**Comment by ZZmarkus** [comment]
YOLO알고리즘의 간단한 프르토타입 모델 동작 시 학습 되어있는 Weight파일이 있는데 이 학습된 파일 용량이 100MB이상입니다.
