### ISSUE TITLE
학습시간이 너무 길어짐

### ISSUE THREAD

**Issue by hohoprince** [kpuce2021/Hyeongdori#15]
18개의 테스트용 데이터를 학습을 시키는 시간이 19000시간정도로 측정됨

학습을 진행하기 전에 설정에 문제가 있는것 같음

설정의 문제가 아니면 더 좋은 성능의 GPU가 있는 컴퓨터로 진행해야함

**Comment by Lee-HyeongSeok** [comment]
AWS 사용해서 학습 시킨건가?
