### ISSUE TITLE
정확도 향상을 위한 알고리즘 변경

### ISSUE THREAD

**Issue by hohoprince** [kpuce2021/Hyeongdori#6]
정확도 향상을 위해 다른 알고리즘을 적용하는 방법을 고려할 필요가 있음

**Comment by hohoprince** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [test](https://trello.com/c/ZbjgVeOj/1-test)

**Comment by Lee-HyeongSeok** [comment]
인공지능 알고리즘 검출률 확보를 위해 기존의 주제와는 다른 데이터 셋을 통한 YOLO 알고리즘 프로토타입 구현 필요 

![cat 1](https://user-images.githubusercontent.com/55940552/105144314-64140400-5b40-11eb-894c-f057cb49ecb3.jpg)
![dog 2](https://user-images.githubusercontent.com/55940552/105144326-68402180-5b40-11eb-867f-2e86702c2865.jpg)

[데이터셋 출처 Cat and Dog](https://www.kaggle.com/tongpython/cat-and-dog?select=training_set)

**Comment by hohoprince** [comment]
Mask R-CNN 알고리즘을 사용해 비교해볼것
